version: 0.2
phases:
  install:
    commands:
      

    pre_build:
      commands:
        - echo "[+] Running tests..."


      build:
        commands:
          - pip3 install -r requirements.txt
      
        post_build:
          commands:
            - echo "Packaging Completed on `data`"
                 
