version: 0.2
phases:
  install:
    commands:
      - sudo apt install python3-pip

    pre_build:
      commands:
        - echo "[+] Running tests..."


      build:
        commands:
          - pip install -r requirements.txt
      
        post_build:
          commands:
            - echo "Packaging Completed on `data`"
                 
